namespace TaqTask.Infrastructure.Services;

public static class DisposableEmailChecker
{
    private static readonly HashSet<string> Domains = new(StringComparer.OrdinalIgnoreCase)
    {
        "mailinator.com", "guerrillamail.com", "10minutemail.com", "tempmail.com",
        "throwaway.email", "yopmail.com", "sharklasers.com", "burnermail.io",
        "trashmail.com", "temp-mail.org", "tempail.com", "maildrop.cc",
        "getnada.com", "mailtemp.net", "discard.email", "spamgourmet.com",
        "mytemp.email", "fakeinbox.com", "mailmetrash.com", "mailexpire.com",
        "tempinbox.com", "throwaway.email", "spambox.us", "temporary-mail.net",
        "mailcatch.com", "spamfree24.org", "spam.la", "ma10.com",
        "mintemail.com", "sofort-mail.de", "mailnator.com", "meltmail.com",
        "sneakemail.com", "maileater.com", "dontreg.com", "spamday.com",
        "spamhereplease.com", "spamherelotso.com", "spamhole.com", "spammotel.com",
        "spamthisplease.com", "speed.1s.fr", "spamcero.com", "spamdecoy.net",
        "spamenuff.com", "spamex.com", "spamfighter.de", "spamgourmet.com",
        "spamkill.info", "spaml.com", "spamlot.net", "spamoff.ftpsite.info",
        "spamstack.net", "spamthis.co.uk", "thankyou2010.com", "trash2009.com",
        "trashymail.com", "tyldd.com", "uggsrock.com", "wegwerfmail.de",
        "wh4f.org", "whyspam.me", "willselfdestruct.com", "winemaven.info",
        "wronghead.com", "wuzup.net", "xagloo.com", "xemaps.com",
        "xents.com", "xmaily.com", "xoxy.net", "yep.it", "yogamaven.com",
        "yopmail.fr", "yopmail.net", "ypmail.webarnak.fr.eu.org",
        "yuurok.com", "zehnminutenmail.de", "zippymail.info", "zoaxe.com",
        "zoemail.org", "temp-mail.org", "tempmail.de", "tempemail.net",
        "0-00.usa.cc", "0-mail.com", "0clickemail.com", "00b2bcr51qv58xgl2qv30",
        "027168.com", "0815.ru", "0815.ry", "0815.su", "0845.ru",
        "1-8.biz", "1ce.us", "1chuan.com", "1mail.ml", "1pad.de",
        "1s.fr", "1st-forms.com", "2.0-00.usa.cc", "2-ch.nerdpol.ovh",
        "2-program.com", "2anom.com", "2dfmail.xyz", "2prong.com",
        "3-6-3.net", "3email.club", "3gmail.org", "3trtretgfrfe",
        "4-n.us", "4gf7d.ga", "4mail.cf", "4mail.ga", "4nextmail.com",
        "5-25.xyz", "5oz.ru", "5x25.com", "6-6-5.xyz", "60minutemail.com",
        "672643.net", "675hosting.org", "679.cc", "7tags.com",
        "9mail.cf", "9ox.net", "a-bc.net", "a45.in", "abusemail.de",
        "abyssemail.com", "abyssmail.com", "ac20mail.in", "acmeco.ga",
        "adbet.co", "adpugh.org", "adsd.org", "adubiz.info",
        "advantageprice.net", "adventunderground.com", "afrobacon.com",
        "ag.us.to", "agtx.ml", "aheadwar.com", "aazsys.com",
        "airporttracking.us", "ak52.ga", "akademiyauspexa.xyz",
        "al-qaeda.us", "albion.online", "alivance.com", "alldirectbuy.com",
        "alole.info", "alph.wtf", "ama-trade.de", "amail.ml",
        "amail4.me", "amazon-aws.org", "amelijkcort.nl", "analogier.com",
        "anonbox.net", "anonymail.dk", "anonymbox.com", "anonymized.org",
        "antichef.com", "antispam24.de", "antispammail.de", "apkm.ai",
        "appixie.com", "armyspy.com", "aron.us", "arur01.tk",
        "asorent.com", "ass.pp.ua", "auctioneer.net", "auti.st",
        "autotwollow.com", "aver.com", "avls.pt", "azmeil.tk",
        "b.qm.pe", "b1of96u.com", "badhus.org", "bangkokhotels.org",
        "bareed.ws", "barging.net", "baric.com", "basscode.org",
        "bauwerke-online.com", "bazaaboom.com", "bbbbyyzz.info",
        "bbhost.us", "bcaoo.com", "beddly.com", "beefmilk.com",
        "belamail.org", "bestchoiceusedcar.com", "bidourlnks.com",
        "bigprofessor.so", "bigstring.com", "binka.me", "binkmail.com",
        "bio-muesli.net", "bione.co", "bitwhites.top", "bko.kiev.ua",
        "blogmyway.org", "bluedumpling.info", "bluewerks.com",
        "bobmail.info", "bobmurchison.com", "bofthew.com", "bonobo.email",
        "bookthemmore.com", "bootybay.de", "boun.cr", "bouncy.email",
        "boximail.com", "boxtemp.com.br", "brandallday.net",
        "breakinspect.com", "brefmail.com", "brennendesreich.de",
        "broadbandninja.com", "bsnow.net", "buff email", "buffermail.com",
        "bulsmail.com", "bundy.lamolatelte.de", "bunsenhoneydew.com",
        "burnthespam.info", "burstmail.info", "businesssolution93.com",
        "businesstheme.cloud", "bussitussi.com", "buzzcompact.com",
        "c2.hu", "c51vsgq.com", "cachedot.net", "californiafitnessdeals.com",
        "camararmada.es", "camping-mail.com", "candymail.de", "canyouhearmenow.cf",
        "card.zp.ua", "cars2.club", "casualdx.com", "ccgtoxmail.com",
        "cek.pm", "cellphoneprogram.com", "cellsite.net", "chacuo.net",
        "chammy.info", "cheap3ddigital.com", "cheaphorde.com",
        "cheesecakehosting.com", "chicharealty.com", "chielo.com",
        "choicemail1.com", "chong-mail.com", "chris.burgercentral.us",
        "cigar-auctions.com", "ckptr.com", "classicalconvert.com",
        "clay.xyz", "clinicatbf.com", "clipmagnet.com", "cliptik.net",
        "clixser.com", "cloud-mail.xyz", "cloudns.cc", "cloudns.cf",
        "cloudns.ga", "cloudns.gq", "cloudns.ml", "cloudns.tk",
        "clrmail.com", "cmail.club", "cmail.com", "cnamed.com",
        "cnovel.com", "co1r.net", "codeandscotch.com", "codivide.com",
        "coieo.com", "coincal.com", "coldemail.info", "compareshippingrates.org",
        "completelyemail.com", "complxmind.com", "contactout.net",
        "contentwanted.com", "cool.fr.nf", "coolimpool.org", "correotemporal.org",
        "cosmorph.com", "courrieltemporaire.com", "coza.ro", "cpsystems.ru",
        "crankhole.com", "crapmail.org", "crastination.de", "crazespaces.pw",
        "crazymailing.com", "crossmailjet.com", "cubicmail.com",
        "cuemail.com", "cuen7ujex.cf", "curryworld.de", "cutout.club",
        "cyber-innovation.club", "cyber-phone.eu", "dacoolest.com",
        "daintly.com", "damnthespam.com", "dammexe.net", "dampflokfreunde.de",
        "dancecloud.com", "danirafsanjani.com", "danydeals.com",
        "darkharvestfilms.com", "daryxfox.net", "dashpad.com",
        "datarca.net", "datazo.ca", "datum2.com", "davidkoh.net",
        "daymail.life", "daymailonline.com", "deadaddress.com",
        "deadchildren.org", "deadfake.cf", "deadfake.ga", "deadfake.ml",
        "deadfake.tk", "deadspam.com", "deagot.com", "dealja.com",
        "deborahlow.com", "deepcleanprocess.com", "defomail.com",
        "degradedfun.net", "delayload.com", "delikkt.de", "der-kombi.de",
        "derkombi.de", "derluxuswagen.de", "despam.it", "despammed.com",
        "devnullmail.com", "dfg6.kozow.com", "dicksinmyan.us", "digitalsanctuary.com",
        "digitex.ga", "dildosfromspace.com", "dim-coin.com", "dinkmail.com",
        "dipanet.com", "disbox.net", "disbox.org", "discard-email.cf",
        "discard.cf", "discard.ga", "discard.gq", "discard.ml",
        "discard.tk", "discardmail.com", "discardmail.de", "dispo.in",
        "dispomail.xyz", "disposable-e.ml", "disposable-email.ml",
        "disposable.cf", "disposable.ga", "disposable.gq", "disposable.ml",
        "disposable.tk", "disposableaddress.com", "disposableemailaddresses.com",
        "disposableinbox.com", "dispose.it", "disposeamail.com", "disposemail.com",
        "dispostable.com", "divermail.com", "diwaq.com", "dlemail.com",
        "dlymail.com", "dnses.ro", "doanart.com", "dob.jp", "dodgeit.com",
        "dodgemail.de", "doiea.com", "dolphinnet.net", "domforfb1.tk",
        "domforfb2.tk", "domforfb3.tk", "domforfb4.tk", "domforfb5.tk",
        "domforfb6.tk", "domforfb7.tk", "domforfb8.tk", "domozmail.com",
        "donemail.ru", "dontsendmeshit.com", "dorotik.us", "dostavka.by",
        "dot-ml.ml", "dot-ml.tk", "dotman.de", "dotmsg.com", "drak.xyz",
        "drivetagdev.com", "drogue.club", "dropcake.de", "droplar.com",
        "dropmail.me", "dsgvo-nicht-vergessen.de", "dsgvo-nicht-vergessen.cf",
        "duam.net", "dudmail.com", "duk33.com", "dump-email.info",
        "dumpandjunk.com", "dumpmail.de", "dumpyemail.com", "duskmail.com",
        "dw.now.im", "dx.abuser.eu", "dyceroprojects.com", "dz17.net",
        "e-mail.com", "e-mail.net", "e-mail.org", "e4ward.com",
        "eastblog.space", "easy-trash-mail.com", "easynetwork.info",
        "easytrashmail.com", "ebeschlussbuch.de", "ecolo-online.fr",
        "edgex.ru", "edrishn.xyz", "edv.to", "eenriet.com", "eezo.pl",
        "eelmail.com", "egz.xyz", "einmalmail.de", "einrot.com", "einrot.de",
        "eintagsmail.de", "elearningjournal.org", "electro.mn",
        "elitevipatlantamodels.com", "email-fake.cf", "email-fake.ga",
        "email-fake.gq", "email-fake.ml", "email-fake.tk",
        "email-jetable.fr", "email-temp.com", "email.cbes.net", "email.net",
        "email.factual.com", "email60.com", "emailage.cf", "emailage.ga",
        "emailage.gq", "emailage.ml", "emailage.tk", "emailate.com",
        "emailcu.icu", "emailde.de", "emaildeals.shop", "emaildienst.de",
        "emaildrop.io", "emailfake.ml", "emailfake.tk", "emailfreedom.ml",
        "emailgenerator.de", "emailgo.de", "emailgov.ru", "emailias.com",
        "emailigo.de", "emailinfive.com", "emailisvalid.com",
        "emaillime.com", "emailmenow.info", "emailmiser.com",
        "emailna.co", "emailo.pro", "emailondeck.com", "emailportal.online",
        "emailproxsy.com", "emailresort.com", "emails.ga", "emails.incisivem",
        "emailsecurer.com", "emailsensei.com", "emailsingularity.net",
        "emailspam.cf", "emailspam.ga", "emailspam.gq", "emailspam.ml",
        "emailspam.tk", "emailspot.org", "emailtemporarios.com",
        "emailthe.net", "emailtmp.com", "emailto.de", "emailtoo.com",
        "emailure.net", "emailwarden.com", "emailx.at", "emailx.net",
        "emailx.org", "emailxmail.com", "emailz.cf", "emailz.ga",
        "emailz.gq", "emailz.ml", "emailz.tk", "emeil.in", "emeil.ir",
        "emil.com", "emial.com", "emz.net", "enayu.com", "envy17.com",
        "ephemail.net", "ephemeral.email", "eqiluxspam.ga",
        "ericjohnsonisadouchebag.com", "esc.la", "escanmail.com",
        "escapehatchapp.com", "eset.tmp@gmail.com", "esprity.com",
        "etgdev.de", "ethereal.email", "ethermail.net", "etranquil.com",
        "etranquil.net", "eu6fncj4w0.ga", "eumx.net", "everytg.ml",
        "evopo.com", "exbte.com", "exdonuts.com", "execs2k.xyz",
        "existiert.net", "exitstageleft.net", "explodemail.com",
        "express.net.ua", "ezlo.co", "ezz.bid", "f4k.es", "faan.de",
        "facebook-email.cf", "facebook-email.ga", "facebook-email.ml",
        "facebookmail.gq", "facebookmail.ml", "fackme.gq", "fag.wf",
        "failbone.com", "faithkills.cf", "faithkills.ga", "faithkills.gq",
        "faithkills.ml", "faithkills.tk", "fake-email.pp.ua",
        "fake-mail.cf", "fake-mail.ga", "fake-mail.ml", "fake.i",
        "fakemail.fr", "fakemail.io", "fakemailgenerator.com",
        "fakemailz.com", "faking.ninja", "fammix.com", "fanclub.pw",
        "fangoh.com", "fansworldwide.de", "fantasymail.de", "fartwallet.com",
        "fast-mail.org", "fastair.info", "fastfrom.com", "fastimap.com",
        "fastkawasaki.com", "fastmailnow.com", "fastmazda.com",
        "fastsuzuki.com", "fastyamaha.com", "fatflap.com", "fbma.tk",
        "fdfdsfds.com", "fer-gabon.org", "fettometern.com", "fiberia.com",
        "ficken.de", "fictionsite.com", "fightallspam.com", "figjs.com",
        "figshot.com", "fiifke.de", "filbert4u.com", "filberts4u.com",
        "film-blog.org", "filzmail.com", "findoc.info", "fintechaber.com",
        "fipr.info", "firemail.cc", "fitnesrezink.com", "fivemail.de",
        "fixmail.tk", "fizmail.com", "flash-mail.ga", "flash-mail.ml",
        "flash-mail.tk", "flashbox.5july.org", "fleckens.hu",
        "flemail.ru", "flirtings.de", "flurred.com", "fly-ts.com",
        "flyspam.com", "foobarbot.net", "footard.com", "forecastertests.com",
        "foreskin.cf", "foreskin.ga", "foreskin.gq", "foreskin.ml",
        "foreskin.tk", "forgetmail.com", "fornow.eu", "forpenguin.com",
        "forward.cat", "foxja.com", "fr.zinbox.com", "fr33mail.info",
        "fragolina2.tk", "frapmail.com", "free-email.cf",
        "free-email.ga", "freebabysittercam.com", "freeblacksmith.com",
        "freebox.com", "freecat.net", "freeletter.org",
        "freemail.cf", "freemail.ga", "freemail.gq", "freemail.ml",
        "freemail.tk", "freemail.tweakly.net", "freemail.ms", "freemails.cf",
        "freemails.ga", "freemails.ml", "freeplumpervideos.com",
        "freeschoolcams.com", "freesugery.com", "freetubearchive.com",
        "freunde.ru", "friendlymail.co.uk", "frogmail.com", "from.onmypc.info",
        "fromearth.net", "front14.org", "fsociety.org", "ftp.sh",
        "fucked.ninja", "fuckingcheapstuff.com", "fuckme69.club",
        "fucknshit.com", "fuckxxme.com", "fulvie.com", "fun64.com",
        "funnycodes.net", "funnymail.de", "furzauflunge.de",
        "fuw65w.cf", "fuw65w.ga", "fuw65w.gq", "fuw65w.ml",
        "fuw65w.tk", "fxprix.com", "g4hdrop.me", "gaggle.email",
        "galaxy.tv", "gally.jp", "gamail.top", "gamil.com", "ganmail.cf",
        "ganmail.ga", "ganmail.gq", "ganmail.ml", "garbage.com",
        "gardenscape.ca", "garliclife.com", "garrifulio.mailexpire.com",
        "gav0.com", "gawab.com", "geekforex.com", "geldwaschmaschine.de",
        "gelitik.in", "genderfuck.net", "gero.us", "geschent.biz",
        "get-mail.cf", "get-mail.ga", "get-mail.ml", "get-mail.tk",
        "get.pp.ua", "get1mail.com", "get2mail.com", "getairmail.com",
        "getmails.eu", "getnada.com", "getnowtoday.cf", "getonemail.com",
        "getonemail.net", "ghosttexter.de", "giacmosuaviet.info",
        "gibraltar.band", "girlncool.com", "girlsindetention.com",
        "gishpuppy.com", "glitch.sx", "globaltouron.com", "glubex.com",
        "glucosegrin.com", "gmai.com", "gmail.com", "gmx.co.uk", "gmx.com",
        "gmx.de", "gmx.net", "gnctr-calgary.com", "go.irc.so",
        "go2usa.info", "go2vpn.net", "godataflow.xyz", "goemail.com",
        "gok.kr", "goldenmail.com", "goldtoolbox.com", "golemico.com",
        "gomail.in", "goodi.club", "googlemail.com", "goplay.com",
        "gorillaswithdirtyarmpits.com", "goround.info", "gotmail.com",
        "gotmail.net", "gotmail.org", "govnomail.xyz", "gppi.org",
        "grabmail.com", "graffiti.net", "gramail.net", "grandmamail.com",
        "grandmasmail.com", "grassdev.com", "great-host.in", "greatmail.com",
        "greebka.com", "greenemail.info", "greensloth.com", "greggamel.com",
        "grish.de", "growlcombine.com", "grr.la", "gsrv.co.uk",
        "gsxstring.ga", "gudangonline.com", "gustore.com", "gx.dl.my",
        "gynzi.co.uk", "gynzy.at", "h1z8ckvz.ga", "h8s.org", "h99.ml",
        "hackersquad.com", "hackthatitch.org", "hahawrong.com",
        "haida-edu.cn", "hallowelt.biz", "haltospam.com", "hamster-man.com",
        "handbag.com", "hangxomcuabom.xyz", "hapin.club", "happysinner.com",
        "happyyou.pw", "harakirimail.com", "hard-core.xyz",
        "hartbot.de", "hash.pp.ua", "hashtagplease.com", "haste.eu",
        "hawrong.com", "hazelnut4u.com", "hazelnuts4u.com", "hbo.com",
        "hdzabgab.xyz", "headstrong.de", "healyourself.xyz", "heathenhammer.com",
        "heavymail.org", "heeco.me", "heisei.be", "hellodream.mobi",
        "helloricky.com", "helpinghandtax.center", "herp.in", "herser.com",
        "hetmail.nl", "hewke.xyz", "hey.to", "hidemail.de", "hidemail.pro",
        "hidemail.us", "hidzz.com", "highbrow.org", "hix.kr", "hjdosage.com",
        "hkhk.de", "hmamail.com", "hoangflong.com", "hochsitze.com",
        "holdup.me", "holyokecode.com", "honestabclot.com", "hopto.org",
        "hornyalwary.com", "horsefucker.org", "horsesforfriends.com",
        "hot-mail.cf", "hot-mail.ga", "hot-mail.gq", "hot-mail.ml",
        "hot-mail.tk", "hotpop.com", "hotprice.co", "housat.com",
        "housemail.com", "hstermail.com", "ht.cx", "huangniu8.com",
        "hukkmu.tk", "hulapla.de", "humaility.com", "humn.ws.gy",
        "hungpackage.com", "hushmail.com", "hvastudies.eu", "i2pmail.org",
        "i6.cloudns.cc", "i6o7c4q2.ga", "ibnuh.bz", "icantbelieveineedtoexplainthissh.it",
        "icemail.club", "icx.in", "idx4.com", "ieatspam.eu", "ieatspam.info",
        "ieh-mail.de", "ige.es", "igg.biz", "ignoremail.com", "ihateyoualot.info",
        "ihazspam.ca", "iheartspam.org", "ikbenspamvrij.nl", "illistnoise.com",
        "ilovespam.com", "imails.info", "imapmail.org", "imgof.com",
        "imgv.de", "imstations.com", "inaby.com", "iname.com", "inbaca.com",
        "inbox.si", "inboxalias.com", "inboxbear.com", "inboxclean.com",
        "inboxclean.org", "inboxed.pw", "inboxhub.me", "inboxkitten.com",
        "inboxproxy.com", "inclusiveprogress.com", "incognitomail.com",
        "incognitomail.net", "incognitomail.org", "ind.st", "indieclad.com",
        "indirect.com", "ineec.net", "infocom.zp.ua", "infomarkets.group",
        "inggo.org", "inmynetwork.cf", "inmynetwork.ga", "inmynetwork.gq",
        "inmynetwork.ml", "inmynetwork.tk", "insanumingeniumhome.com",
        "insorg-mail.info", "instafun.ml", "instaku-media.com",
        "instant-mail.de", "instant.email", "instantblingmail.info",
        "instantmail.de", "instantmail.fr", "internet-v-stavropole.ru",
        "internetoftags.com", "interserver.ga", "intersteller.com",
        "io.ecreate.nl", "ip6.li", "ipoo.org", "irrlab.com", "is.af",
        "isdaq.com", "isosq.com", "ist-einmalig.de", "ist-ganz-allein.de",
        "ist-will-nur.de", "it7.ovh", "italy-mail.com", "itunesgiftcode.gq",
        "ixx.io", "j-p.us", "j3l4a2x2.ga", "jajxz.com", "jderobot.com",
        "jdmadventures.com", "jeeq.pw", "jellowize.com", "jmail.ovh",
        "jncdegg.site", "jnyq.net", "jobbiksz.com", "jobposts.net",
        "jobs-to-be-done.net", "jobseekers.com", "joseihorumon.info",
        "journalist.com", "jp.ftp.sh", "jpanime.net", "jpco.org",
        "jungkamushukum.com", "junk.to", "junk1e.com", "junkmail.ga",
        "junkmail.gq", "just-email.com", "just4spam.com", "justbegood.net",
        "justemail.ml", "jzexport.com", "k2-hermes.com", "kademen.com",
        "kadokawa.cf", "kaffeeschluerfer.com", "kah.pw", "kamenet.ru",
        "kamsg.com", "kaplay.com", "kappala.info", "karbasi.net",
        "karin.xyz", "kartvelo.me", "kasumay.com", "kaszma.com",
        "katharina-niggemeier.de", "kebi.com", "keepmymail.com",
        "keinhirn.de", "keipino.de", "kekita.com", "kemptvillebaseball.com",
        "kennedy808.com", "kiani.com", "killmail.com", "killmail.net",
        "kimsdisk.com", "kismail.com", "kisstwink.com", "kitnastar.com",
        "klassmaster.com", "klassmaster.net", "klerk.xyz", "klick-tipp.us",
        "klipschx12.com", "klopptwop.de", "kms.ds", "knol-power.nl",
        "kobrandify.com", "kook.ml", "koparet.ru", "koshu.ru",
        "kostenlosmail.com", "koszmail.pl", "krypton.tk", "kuhrap.com",
        "kulmeo.com", "kulturbetrieb.info", "kurr.de", "kusrc.com",
        "kuy.ml", "l33r.eu", "l6 факторов", "labetteraverouge.at",
        "labo.ch", "lacedmail.com", "lacto.info", "lags.us", "land-4-sale.us",
        "larsen2010.com", "last-chance.pro", "lastmail.co", "lastmail.com",
        "latemails.com", "lavabit.com", "lawlita.com", "laym.pw",
        "lazyinbox.com", "lazyinbox.us", "leapradius.com", "left.ru",
        "legalrc.loan", "lellno.gq", "lenus.online", "lerch.ovh",
        "letmeinonthis.com", "letthemeatspam.com", "lexisense.com",
        "lez.se", "lgxscreen.com", "liamcyrus.com", "lifebyfood.com",
        "lifetimefriends.info", "ligsb.com", "lillemap.net", "link2mail.com",
        "linkedintuts2016.pw", "litedrop.com", "liveradio.tk", "ljiljane.com",
        "llandudno-pier.com", "ln0x.de", "loadby.us", "loan101.pro",
        "loanss.space", "loaoa.com", "loapq.com", "loh.pp.ua",
        "lol.ovpn.to", "lolfisher.com", "lolmail.tk", "lom.kr",
        "lookformail.cf", "lookformail.ga", "lookformail.gq", "lookformail.ml",
        "lookformail.tk", "lopl.co.cc", "lostpositive.net", "lottemails.com",
        "louis.xyz.net", "loves.dicksinhisan.us", "loves.dicksinmyan.us",
        "luckymail.org", "lukecarriere.com", "luksar.net", "luky.org",
        "luv2.us", "lydiagwilt.net", "lyfestylecredits.com",
        "m0ybfq3j.ga", "m4ilweb.info", "m4n.ml", "maboard.com",
        "macr2.com", "macromaid.com", "macromice.com", "magamail.com",
        "magemamail.com", "magicbox.ro", "magspam.net", "maido.pw",
        "mail-2-you.com", "mail-4.de", "mail-8.com", "mail-awt.de",
        "mail-box.com", "mail-c.tk", "mail-on.us", "mail-page.com",
        "mail-r.eu", "mail-t.tk", "mail.backflip.net", "mail.bccto.com",
        "mail.bccto.me", "mail.cbdf.xyz", "mail.chrismjm.net",
        "mail.com", "mail.fettometern.com", "mail.gen.pw", "mail.ht",
        "mail.md", "mail.mixx.xyz", "mail.mountainregionallibrary.net",
        "mail.org", "mail.partskyline.com", "mail.piaa.me",
        "mail.scarletcloud.net", "mail.svenz.eu", "mail.usa.com",
        "mail.wtf", "mail0.ga", "mail1.dr56.pw", "mail1.i-dee.org",
        "mail1.ml", "mail114.net", "mail15.com", "mail199.locum.ru",
        "mail1a.de", "mail1web.org", "mail2.0-00.usa.cc", "mail2.dr56.pw",
        "mail2rss.org", "mail2space.com", "mail22.club", "mail22.space",
        "mail2tor.com", "mail333.com", "mail4-us.org", "mail4trash.com",
        "mail666.ru", "mail7.xyz", "mail707.com", "mail72.com",
        "mailapp.com", "mailbiz.biz", "mailblocks.com", "mailblog.biz",
        "mailbox2go.com", "mailbox80.cf", "mailbox80.ga", "mailbox80.gq",
        "mailbox80.ml", "mailbox80.tk", "mailboxmail.net", "mailbucket.org",
        "mailcat.biz", "mailcatch.com", "mailcell.net", "mailchop.com",
        "mailcker.com", "mailclick.net", "mailclip.net", "mailde.de",
        "mailde.info", "maildrop.cc", "maileater.com", "mailec.cloud",
        "maileimer.de", "mailexpire.com", "mailfa.tk", "mailfall.com",
        "mailfence.com", "mailforspam.com", "mailfree.ga", "mailfree.gq",
        "mailfree.ml", "mailfree.tk", "mailfs.com", "mailgc.com",
        "mailgov.info", "mailguard.me", "mailgutter.com", "mailhazard.com",
        "mailhazard.us", "mailhex.com", "mailhub.pro", "mailhz.me",
        "mailimate.com", "mailin8r.com", "mailinatar.com", "mailinbox.cf",
        "mailinbox.co", "mailinbox.ga", "mailinbox.gq", "mailinbox.ml",
        "mailinbox.tk", "mailing.one", "mailismagic.com", "mailita.tk",
        "mailjunk.org", "mailjuice.space", "mailmate.com", "mailme.ga",
        "mailme.gq", "mailme.ml", "mailme.tk", "mailme24.com",
        "mailmetrash.com", "mailmoat.com", "mailmoth.com", "mailms.com",
        "mailnator.com", "mailna.win", "mailnet.cf", "mailnet.ga",
        "mailnet.gq", "mailnet.ml", "mailnet.tk", "mailnow2.com",
        "mailnowapp.com", "mailnuo.com", "mailnw.de", "mailonaut.com",
        "mailorator.com", "mailorg.org", "mailox.fun", "mailpick.biz",
        "mailpooch.com", "mailpremium.net", "mailproxsy.com",
        "mailquack.com", "mailrocket.org", "mailsac.com", "mailscrap.com",
        "mailseal.de", "mailsent.net", "mailservice.ms", "mailshiv.com",
        "mailshuttle.com", "mailsiphon.com", "mailslapping.com",
        "mailspam.xyz", "mailspamtest.com", "maistupid.com",
        "mailsuck.org", "mailt.net", "mailt.one", "mailtag.com",
        "mailtemp.info", "mailtemp.net", "mailtempmx.com", "mailtemporaire.com",
        "mailtemporaire.fr", "mailto.plus", "mailtothis.com",
        "mailtraps.com", "mailtrash.net", "mailtrix.net", "mailtv.net",
        "mailtv.tv", "mailuniverse.co.uk", "mailv3.com", "mailvc.com",
        "mailvn.net", "mailwizz.com", "mailx.tk", "mailxp.net",
        "mailz.info", "mailzer.net", "mainerfolg.info",
        "makemenaughty.com", "makepleasure.com", "malamail.cf",
        "malayalamdtp.com", "mamao.info", "mansiondev.com", "manybrain.com",
        "markmurfin.com", "masonline.info", "maswae.world", "matra.site",
        "max-mail.com", "maxturns.com", "mb14.net", "mbf.cc",
        "mciek.com", "mdh2011.org", "mdhc.tk", "meantinc.com",
        "mechanicalresumes.com", "medbotz.com", "medizin-optik.com",
        "meepsheep.eu", "meinspamschutz.de", "meltmail.com", "memsg.site",
        "menschenso.de", "messagebeagle.de", "messwiththebestdielikethe.rest",
        "mhmm.xyz", "miaferrari.com", "midcoastcustoms.com",
        "midcoastcustoms.net", "midlertidig.com", "midlertidig.net",
        "midnightmail.org", "migmail.net", "migmail.pl", "migumail.com",
        "mijnhqmail.nl", "mikaela.net", "mikrotamanet.com", "mim.ooo",
        "mindless.com", "mine.nu", "mintemail.com", "misterpinball.com",
        "mixmail.com", "mjf.io", "mji.ro", "mjukglass.nu",
        "mkb-endeavour.com", "mksecrets.net", "ml-sf.eu", "mlo.kr",
        "mlx.ovh", "mm.5-25.xyz", "mmf.ovh", "mmj.it", "moakt.co",
        "moakt.com", "moakt.ws", "mobileninja.co.uk", "mobilevpn.top",
        "mobiplus.com", "moburl.com", "mockmyid.com", "moeri.org",
        "mohmal.com", "mohmal.im", "mohmal.in", "mohmal.tech",
        "moiamin.com", "molms.com", "momentics.ru", "moncourrier.fr.nf",
        "monemail.com", "monemail.fr.nf", "monmail.fr.nf",
        "monumentmail.com", "moonwake.com", "moot.es", "moreawesomethanyou.com",
        "moreorcs.com", "morriesworld.ml", "mortaljoe.com", "mortensen911.com",
        "mosout.com", "mountainregionallibrary.net", "moza.pl",
        "msgden.com", "msgos.com", "msgsafe.ninja", "msn.com",
        "msndcx.com", "msrc.ml", "mssr.ml", "msvhosting.nl",
        "mt2009.com", "mt2014.com", "mt2015.com", "mtmdev.com",
        "muathe.xyz", "muchomail.com", "mucuy.com", "muellemail.com",
        "muell.xyz", "mufux.com", "mugglenet.org", "muimail.com",
        "mullme.com", "multiplechoices.net", "munoubengoshi.gq",
        "muscleguy.net", "muskelshirt.de", "mustbedestroyed.org",
        "mutant.me", "mwarner.org", "mxfuel.com", "my-pomsies.com",
        "my-teddyy.com", "my.usa.cc", "my10minutemail.com",
        "myalias.pw", "mycard.net.ua", "mycleaninbox.net",
        "mycorneroftheinter.net", "myemail.com", "myemail.net",
        "myemailboxy.com", "mykickassideas.com", "mymail.com",
        "mymail.in.th", "mymail.oasis.com", "mymailcrush.cf",
        "mymailcrush.ga", "mymailcrush.gq", "mymailcrush.ml",
        "mymailcrush.tk", "mymailoasis.com", "myneocards.cz",
        "mynetstore.de", "myopang.com", "mypacks.net", "mypartyclip.de",
        "myphantomemail.com", "mysamp.de", "myspaceinc.com",
        "myspaceinc.net", "myspaceinc.org", "myspacepimporginul.com",
        "myspamless.com", "mystvpn.com", "mytemp.email", "mytempemail.com",
        "mytruemail.net", "mywarnernet.net", "myzx.com", "n1nja.org",
        "n2s0.com", "n8.gs", "nabuma.com", "nada.email", "nada.ltd",
        "nafe.com", "nakedtruth.biz", "nanonym.ch", "naskot.com",
        "natty.xyz", "naturalious.com", "nawmin.info", "nbzmr.com",
        "neadr.xyz", "neb.r.healthemail.com", "nedersaksisch.nl",
        "neeva.net", "negated.com", "neiroo.com", "neko2.net",
        "neomailbox.com", "neotrade.xyz", "nepwk.com", "nervmich.net",
        "nervtmich.net", "net.xyz", "netemail.com", "netmail.cf",
        "netmail.ga", "netmail.gq", "netmail.ml", "netmail.tk",
        "netmails.com", "netmails.net", "netricity.nl", "netris.net",
        "netscape.net", "netspam.xyz", "neverbox.com", "nevermail.de",
        "newbpotato.tk", "newideasfornewpeople.com", "newmail.co",
        "newmail.in", "newsmatic.us", "next.ovh", "nextderm.com",
        "nextstopvalhalla.com", "nezdiro.org", "nezid.com",
        "nfz.us", "nguyenusedcars.com", "nicebush.com", "nicebush.org",
        "nicemail.com", "nicknassar.com", "nincsmail.com", "nipissinit.eu",
        "niwl.net", "nm.cm", "nm7.cc", "nmail.cf", "no-more-mail.com",
        "no-vax.cf", "no-vax.ga", "no-vax.gq", "no-vax.ml",
        "no-vax.tk", "noblegrow.com", "nobulk.com", "noclickemail.com",
        "nodezine.com", "nogmailspam.info", "noicd.com", "nokiamail.com",
        "nolemail.ga", "nom.za", "nomail.cf", "nomail.ga", "nomail.gq",
        "nomail.ml", "nomail.tk", "nomail.xl.cx", "nomail2me.com",
        "nomorespamemails.com", "nonspam.eu", "nonspammer.de",
        "nonze.ro", "noref.in", "norriserscheinen.com", "nospam.ze.tc",
        "nospam4.us", "nospamfor.us", "nospammail.net", "nospamthanks.info",
        "nothingtoseehere.ca", "notmail.com", "notmail.net",
        "notmail.org", "notrnailinator.com", "notsharingmy.info",
        "now.im", "nowmymail.com", "ntlhelp.net", "ntoll.org",
        "nubescontrol.com", "nullbox.info", "nur-fuer-spam.de",
        "nus.edu.sg", "nuo.co.kr", "nut.cc", "nutpa.net", "nvkoiylc.xyz",
        "nwldx.com", "nwytg.net", "nxc8.com", "nxxe.tk", "o0i.es",
        "o.cfo2.xyz", "o2t4g.org", "o7i.net", "oalsp.com",
        "obfusko.com", "objectmail.com", "obobbo.com", "obxpestcontrol.com",
        "odaymail.com", "odnorazovoe.ru", "oepia.com", "oerpub.org",
        "offworld.online", "oiqbv.com", "okclprojects.com", "okrentewebsite.com",
        "okzk.com", "olypmall.ru", "omail.pro", "omnievents.org",
        "one-time.email", "oneoffmail.com", "onewaymail.com", "onlatedotcom.com",
        "onlineanal.cc", "onmail.win", "onmailzone.com", "onnot.info",
        "oopi.org", "opayq.com", "openmailbox.org", "opentrash.com",
        "opmmedia.ga", "opp24.com", "ordinaryamerican.net", "orgmbx.cc",
        "oshietechan.link", "otherinbox.com", "ourl.in", "outlook.com",
        "outlok.com", "ov3u841.com", "ovsoftmail.com", "owlpic.net",
        "ownsyou.de", "oxfarm1.com", "oxyfly.co.uk", "ozbytes.net",
        "ozz.ru", "p71ce1m.com", "pa9e.com", "pachilly.com",
        "pacman-gamer.com", "paddedma.com", "pads.ma", "pagamenti.tk",
        "pakadebu.ga", "pancakemail.com", "papierkorb.me", "parlimentpetitions.com",
        "pastebitch.com", "paulfucksallthebitches.com", "payperexclusives.com",
        "pc1518.com", "pclobberguey.com", "pecinan.com", "pecmail.xyz",
        "pedestrian.com", "pencalc.com", "penis.computer", "penoto.tk",
        "pepbot.com", "peterdethier.com", "petertijj.com", "petranchr.com",
        "pfui.ru", "phonearea.top", "photo-impact.eu", "photomark.net",
        "phpbb.uu.gl", "phuongblue.com", "pi.0-00.usa.cc", "piaa.me",
        "pig.pp.ua", "piki.si", "pimpedupmyspace.com", "pingir.com",
        "pinoywatch.com", "pipeline.com", "piratehaven.org", "pivo.de",
        "pizzanomics.site", "pjjkp.com", "placemailon.com", "pleasure-club.de",
        "pleasurepoint.de", "plmonline.club", "pluno.com", "plusmail.com.br",
        "pmcl.net.au", "poczta.onmypc.info", "podam.pl", "pokemail.net",
        "polarkingxx.ml", "politikerclub.de", "pooae.com", "poofy.org",
        "pookmail.com", "poopiebutt.club", "pop3.xyz", "popmail.com",
        "popsmack.com", "porewap.com", "poutineyourface.com", "powered.name",
        "poweredniche.com", "powlearn.com", "pp.ua", "pqoia.com",
        "pr-cash.com", "prankmail.fr", "prankmail.xyz", "premium-mail.fr",
        "priest.com", "primelime.com", "primitus.com", "printfection.com",
        "privacy.net", "privatdemail.net", "privy-mail.com", "privymail.de",
        "pro.cloudns.asia", "pro.store", "procrackers.com", "projectcl.com",
        "promail.com", "promails.xyz", "promotepace.com", "proxymail.eu",
        "prtnx.com", "prtz.eu", "psci.net", "pseshop.com", "puffsage.com",
        "puk.us.to", "puki.xyz", "pullcombine.com", "purple.ftp.sh",
        "pushmojo.com", "putama.com", "puttanamaiala.it", "pw.epac.to",
        "pw.fluid.com", "pwp.lv", "pwrby.com", "q13.de", "qbfox.com",
        "qibl.at", "qipmail.net", "qiq.us", "qisdo.com", "qisoa.com",
        "qmrbe.com", "qoika.com", "qq.my", "qsl.ro", "quadrafit.com",
        "quick-mail.info", "quickinbox.com", "quickmail.in", "quickmail.nl",
        "quin.xyz", "qvy.me", "qwickmail.com", "qzc.co.za",
        "r0.igg.biz", "r1pp.ga", "r1pp.gq", "r1pp.ml", "r2cakes.com",
        "r4sale.eu", "r8.igg.biz", "raak.xyz", "rabin.ca", "rabiot.reisen",
        "rackabzar.com", "raetp.com", "rainbowly.ml", "rainmail.biz",
        "rainwaterstudios.org", "raketenmail.de", "rancidhome.net",
        "randomail.net", "raptors.beer", "rasmussen.ml", "rastogi.xyz",
        "rawmails.com", "rcpt.at", "rd.ctos.xyz", "re-gister.com",
        "react2.com", "realty-alerts.com", "receiveee.com", "reclaim.my",
        "recode.me", "recursor.net", "recyclemail.dk", "reddcoin.com",
        "redfeathercrow.com", "redirectmethod.com", "redmail.xyz",
        "refreshingbox.com", "reftoken.net", "regbypass.com", "regspaces.tk",
        "rejectall.com", "reliable-mail.com", "remail.cf", "remail.ga",
        "remote.li", "reptilegenetics.com", "res.craigslist.org",
        "resgedcomfedex.cf", "resgedcomfedex.ga", "resgedcomfedex.gq",
        "resgedcomfedex.ml", "resgedcomfedex.tk", "resistaries.info",
        "retardbitch.org", "retemail.com", "returntohell.info",
        "revolvingdoorhoax.org", "rhyta.com", "richardsonfm.com",
        "riddermark.de", "rifkiamordeth.com", "rklips.com", "rkomo.com",
        "rma.ec", "rmqkr.net", "rnailinator.com", "ro.lt", "robertspcrepair.com",
        "roboemail.com", "rollindo.agency", "ronnierage.net", "rootfest.net",
        "rotaniliam.com", "rotbox.xyz", "royal.net", "royaldoodles.org",
        "rppkn.com", "rq1.in", "rswz.xyz", "rtotlmail.xyz", "rtrtr.com",
        "rudymail.ml", "runi.ca", "rupayamail.com", "rustydoor.com",
        "rvb.ro", "s0ny.net", "s1x.igg.biz", "s3.igg.biz", "s33d.eu",
        "s3w4q6v5.ga", "s6.igg.biz", "sa.igg.biz", "sabrestlouis.com",
        "sackmail.org", "safamail.ga", "safetymail.info", "safetypost.de",
        "saharanightstempe.com", "saicamilo.com", "sale-gpu.com",
        "salesperson.net", "salmeow.tk", "sameshel.com", "san.can",
        "sandwhichvideo.com", "sanfinder.com", "sanim.net", "sanstr.com",
        "sast.ro", "satukosong.com", "sausen.com", "saynotospams.com",
        "scatmail.com", "schachcomplex.com", "schafmail.de",
        "schmeisswege.de", "schrott-email.de", "scrsot.com", "scubadiving.com",
        "sd3.in", "secmail.pw", "secretarea.net", "secure-box.info",
        "secure-mail.cc", "secured-link.net", "securehost.com.es",
        "seekapps.com", "seekfindask.com", "sejaa.net", "selfdestructingmail.com",
        "sellings.xyz", "send22u.info", "sendfree.org", "sendingspecialflyers.com",
        "sendspamhere.com", "sent.as", "sent.at", "sent.com",
        "sentral.com", "seoblackhat.com", "seomastergroup.com",
        "server.ms", "services391.com", "sexmagnet.com", "sexxican.com",
        "sghtr.xyz", "shahrobazar.com", "sharewaredevelopers.com",
        "sharklasers.com", "shatelkitchen.com", "sheryli.com",
        "shhmail.com", "shhuut.org", "shieldedmail.com", "shieldsemail.com",
        "shiftmail.com", "shipfromto.com", "shiphazmat.org",
        "shipping-regulations.com", "shippingterms.org", "shirakiya.com",
        "shmeriously.com", "shortmail.net", "shotmail.com", "showslow.de",
        "shrib.com", "shwaws.com", "siberask.com", "sidelka.ru",
        "siftportal.ru", "sify.com", "sigaret.net", "sign-up.website",
        "sika3.com", "sikomo.com", "silsym.com", "silvercoin.life",
        "sim-simka.ru", "simaen.com", "simpleitsecurity.info",
        "sin.cl", "sinfiltro.cl", "sinnlos-mail.de", "sirninjalot.com",
        "sirv.com", "siteposter.com", "six6.eu", "sizzlemctwizzle.com",
        "sjuaq.com", "skeefmail.com", "skrx.tk", "sky-inbox.com",
        "skymailapp.com", "skypaluten.de", "slapsfromlastnight.com",
        "slaskpost.se", "slaughterhouse.com", "slipperybrick.com",
        "slipry.net", "slo.net", "slopsmail.com", "slushmail.com",
        "sly.io", "smallker.tk", "smap.4nmv.ru", "smap.4nmv.ru",
        "smashmail.de", "smellfear.com", "smellrear.com", "smellypotato.tk",
        "smtp99.com", "smwg.info", "snaknoc.com", "snapunit.com",
        "snkmail.com", "social-mailer.tk", "socialfurry.org",
        "sofimail.com", "sofort-mail.de", "softkey-germany.de",
        "sofort-mail.de", "sofortmail.de", "softpls.asia", "sogetthis.com",
        "sohai.ml", "sohus.cn", "soio.de", "soldieroftheinternet.com",
        "solluna.info", "soloveo.com", "solution4u.com", "solvemail.info",
        "songwriter.net", "sonicmail.com", "sonshi.cf", "sonshi.ga",
        "sonshi.gq", "sonshi.ml", "sonshi.tk", "soodmail.com",
        "soodonims.com", "soon.it", "soulhacker.com", "sourceforge.com",
        "sourceforge.net", "space.com", "spacebazzar.ru", "spam-be-gone.com",
        "spam-cleaner.com", "spam-corner.com", "spam-delete.com",
        "spam-ex.com", "spam-free.eu", "spam-free24.com", "spam-free24.eu",
        "spam-free24.net", "spam-free24.org", "spam-go.ru", "spam-hub.com",
        "spam-lists.com", "spam-net.eu", "spam-shelter.com",
        "spam-snake.com", "spam-stop.com", "spam-sweeper.com",
        "spam-wegwerfmail.org", "spam.as", "spam.biz", "spam.com",
        "spam.de", "spam.deliver.com", "spam.fassagforpresident.ga",
        "spam.fassagforpresident.ml", "spam.fassagforpresident.tk",
        "spam.flu.cc", "spam.igg.biz", "spam.la", "spam.net",
        "spam.org", "spam.su", "spam.usa.cc", "spam.wtf",
        "spam4.me", "spamail.de", "spamarrest.com", "spamavert.com",
        "spambob.com", "spambob.net", "spambob.org", "spambog.com",
        "spambog.de", "spambog.net", "spambog.ru", "spambooger.com",
        "spambox.info", "spambox.irishspringrealty.com", "spambox.me",
        "spambox.org", "spambox.us", "spambox.xyz", "spamcannon.com",
        "spamcannon.net", "spamcero.com", "spamcon.org", "spamcorptastic.com",
        "spamcowboy.com", "spamcowboy.net", "spamcowboy.org",
        "spamday.com", "spamdecoy.net", "spameater.com", "spameater.org",
        "spamex.com", "spamfighter.de", "spamfighter.cf", "spamfighter.ga",
        "spamfighter.gq", "spamfighter.ml", "spamfighter.tk",
        "spamfree.eu", "spamfree24.com", "spamfree24.de",
        "spamfree24.eu", "spamfree24.info", "spamfree24.net",
        "spamfree24.org", "spamgoes.in", "spamgourmet.com",
        "spamgourmet.net", "spamgourmet.org", "spamhereplease.com",
        "spamherelotso.com", "spamhole.com", "spamify.com", "spaminator.de",
        "spamkill.info", "spaml.com", "spamlot.net", "spammail.com",
        "spammail.me", "spammotel.com", "spamobox.com", "spamoff.ftpsite.info",
        "spamout.org", "spamsalad.in", "spamserver.info",
        "spamserver.net", "spamserver.org", "spamslice.com", "spamsphere.com",
        "spamspot.com", "spamstack.net", "spamster.org", "spamthis.co.uk",
        "spamthisplease.com", "spamtrail.com", "spamtrap.net",
        "spamtroll.net", "spamwc.de", "spamwc.ga", "spamwc.gq",
        "spamwc.ml", "spamx.su", "spamzilla.net", "sparbeit.com",
        "spartapost.com", "spazmail.com", "spec-achats.fr", "spectro.icu",
        "speed.1s.fr", "speedgaus.net", "sperma.cf", "spikio.com",
        "spindl-e.com", "spybox.de", "squizzy.net", "squizzy.info",
        "sri.cloud", "sry.li", "ssoia.com", "stanford-edu.tk",
        "starlight-breaker.net", "startfu.com", "startkeys.com",
        "statdvr.com", "stathost.net", "statiix.com", "steam-area.com",
        "steambot.net", "stexsy.com", "stinkefinger.net", "stop-my-spam.com",
        "stopdropandroll.com", "storj99.com", "storj99.top", "streetwisemail.com",
        "stromox.com", "stuckmail.com", "stuffmail.de", "subaru.im",
        "suburbanthug.com", "suckmyd.com", "suckmydick.com",
        "sudur.info", "sugarrape.com", "sui.li", "suioe.com",
        "super-auswahl.de", "supergreatmail.com", "supermailer.jp",
        "superplatyna.com", "superrito.com", "superstachel.de",
        "surfmail.tk", "susi.ml", "sutann.us", "sute.jp",
        "svip520.cn", "svk.jp", "swissmail.com", "swordspider.com",
        "sylvannet.com", "syspac.info", "system-2121.com", "system-2211.com",
        "syujob.accountants", "tafmail.com", "tafoi.gr", "tagmymedia.com",
        "tagyourself.com", "talkinator.com", "tanukis.org", "taphear.com",
        "tastydentures.com", "tatarados.com", "tb-on-line.net", "tbar.xyz",
        "tch.ki", "te.cx", "techemail.com", "techfevoip.com",
        "techgroup.me", "teerest.com", "teewars.org", "tehg.com",
        "teleosaurs.xyz", "teleworm.com", "teleworm.us", "tellos.xyz",
        "temp-emails.com", "temp-mail.com", "temp-mail.de",
        "temp-mail.org", "temp-mail.pp.ua", "temp-mail.ru",
        "temp-mails.com", "temp.ankWebsite.xyz", "temp.headstrong.de",
        "temp.oikpost.com", "temp.weekwill.com", "temp.zehmail.xyz",
        "temp2.org", "tempail.com", "tempalt.com", "tempdomain.net",
        "tempe-mail.com", "tempemail.biz", "tempemail.co.za",
        "tempemail.com", "tempemail.net", "tempemail.org",
        "tempemailaddress.com", "tempemails.net", "tempinbox.co.uk",
        "tempinbox.com", "tempmail.co", "tempmail.de", "tempmail.eu",
        "tempmail.it", "tempmail.net", "tempmail.us", "tempmail.win",
        "tempmail.ws", "tempmail2.com", "tempmaildemo.com",
        "tempmailer.com", "tempmails.org", "tempmailz.com",
        "tempomail.fr", "temporarily.com", "temporarioemail.com.br",
        "temporary-email.com", "temporary-email.net",
        "temporary-email.org", "temporary-forwarding.com",
        "temporarymail.org", "temporarymailaddress.com",
        "tempr.email", "tempres.ml", "tempsky.com", "tempthe.net",
        "tempymail.com", "temtulsa.net", "terb.com", "ternakpedia.site",
        "testohata.xyz", "tewrt.xyz", "texacolor.com", "thangber.com",
        "thanksnospam.info", "thankyou2010.com", "thc.st", "theaperture.net",
        "theaviors.com", "thebearshark.com", "thecity.biz",
        "thecloudindex.com", "thediamondsclub.com", "thedirhq.info",
        "thej5.com", "thelimestones.com", "thembones.com.au",
        "themostemail.com", "theopposition.club", "thepengu.com",
        "thepleasureclub.de", "thepyxis.com", "theradius.info",
        "thescrappermovie.com", "theskymail.com", "theslatch.com",
        "thespamfather.com", "thestreetfighter.com", "thetebowingplace.com",
        "thexte.info", "thietbimaycongnghiep.com", "thisisnotmyrealemail.com",
        "thismail.net", "thisurl.com", "thnikka.com", "thraml.com",
        "thrma.com", "throam.com", "thrott.com", "throwam.com",
        "throwaway.email", "throwaway.io", "throwaway.xyz",
        "throwawayemail.com", "throwawayemailaddress.com",
        "throya.com", "thrubay.com", "thundermail.me", "tizi.com",
        "tkeiyo.com", "tlpn.org", "tmail.com", "tmail.run",
        "tmail.ws", "tmailinator.com", "tmails.net", "tmpeml.info",
        "tmpmail.net", "tmpmail.org", "toddsbighug.com", "toiea.com",
        "tokem.co", "tokenmail.de", "tonne.to", "toofake.com",
        "toohu.us", "top101.de", "top1mail.ru", "top1post.ru",
        "topatopi.com", "topical88.com", "topinrock.cf", "topmail.com",
        "topmail.ml", "topofertasdehoy.com", "topranklist.de",
        "tormail.org", "toss.pw", "totalvista.com", "totoan.net",
        "tough.biz", "tqoai.com", "tqosi.com", "tracker-server.com",
        "tracking.top1server.eu", "tralalajos.ga", "tranceversal.com",
        "trash-2009.com", "trash-2010.com", "trash-mail.com",
        "trash-mail.de", "trash-me.com", "trash.cat", "trash2009.com",
        "trash2010.com", "trash2011.com", "trash247.com", "trashbox.eu",
        "trashcanmail.com", "trashdevil.com", "trashdevil.de",
        "trashemail.de", "trashemails.de", "trashturkiye.com",
        "trashimail.de", "trashmail.at", "trashmail.com",
        "trashmail.de", "trashmail.io", "trashmail.me", "trashmail.net",
        "trashmail.org", "trashmail.ws", "trashmailer.com",
        "trashmails.com", "trashspam.com", "trashymail.com",
        "trashymail.net", "trasz.com", "trayna.com", "trbvm.com",
        "trbvn.com", "trbvo.com", "trgovinavelikani.com",
        "trialmail.de", "trickmail.net", "trillianpro.com",
        "trimsj.com", "trobertqs.com", "trollproject.com", "tropicalbass.info",
        "trump.cheap", "trungtamtoeic.com", "tryalert.com",
        "tryninja.io", "tryprice.co", "turoid.com", "turual.com",
        "tverya.com", "twinmail.de", "twkly.ml", "twocowmail.net",
        "twoweird.com", "twzhhq.online", "tyldd.com", "txcct.com",
        "typestring.com", "uacro.com", "uafdvzq.ml", "ubismail.net",
        "ucupdong.ml", "uemail99.com", "ugly.asia", "uggsrock.com",
        "uguuchantele.com", "uhhu.ru", "uiu.us", "ujijima1129.gq",
        "ukexample.com", "umail.net", "ummahserver.com", "umpire.com",
        "unbounded.ga", "unforgettablefamily.com", "unicorn.com",
        "unimark.org", "unit7lahaina.com", "unmail.ru", "uogg.xyz",
        "upliftnow.com", "uplipht.com", "uploadnolike.com", "upozowas.pp.ua",
        "uprinse.com", "uradio.ga", "uradio.ml", "urbanchickencoop.com",
        "ureee.us", "urfunny.net", "urhen.com", "uroid.com",
        "us.af", "us.issas.xyz", "us.to", "usa.cc", "usako.net",
        "uscaves.com", "uselessness.us", "ushijima1129.cf",
        "ushijima1129.ga", "ushijima1129.gq", "ushijima1129.ml",
        "ushijima1129.tk", "usma.net", "utiket.com", "uu.gl",
        "uujama.com", "uwork4.us", "ux.dob.jp", "uyhip.com",
        "vaasfc4.tk", "valemail.net", "valhalladev.ml", "vampy.gq",
        "vanackercars.com", "vanbil.tk", "vanillacream.com", "vankin.de",
        "vctel.com", "vdaemail.com", "vdigx.com", "vedula.com",
        "velnet.co.uk", "velutispam.cf", "velutispam.ga", "velutispam.gq",
        "velutispam.ml", "velutispam.tk", "venompen.com", "ver0.cf",
        "ver0.ga", "ver0.gq", "ver0.ml", "ver0.tk", "vercelli.cf",
        "vercelli.ga", "vercelli.gq", "vercelli.ml", "vercelli.tk",
        "verdejo.com", "veryday.ch", "veryday.eu", "veryday.info",
        "veryfre.email", "veryrealemail.com", "vesa.pw", "vfemail.net",
        "vickaentb.com", "vidchart.com", "videotubegames.com",
        "viewcastmedia.com", "viewcastmedia.net", "vifiac.com",
        "vikingsonly.com", "vinthie.com", "vip-mail.tk", "vip.cool",
        "vipcctvpcctv.com", "vipmail.name", "vipmail.pw",
        "vipxm.net", "vizmd.cloud", "vjtim.com", "vkusnoisho.ru",
        "vmailing.info", "vmani.com", "vmpanda.com", "vnedu.me",
        "voidbay.com", "volaj.com", "voltaer.com", "vomito.email",
        "vorgsdemail.ml", "vorgsdemail.tk", "vorstavka.ru", "votiputox.org",
        "voxel.cheap", "vpn.st", "vps30.com", "vps911.net",
        "vpsorg.cloud", "vpsorg.pro", "vpsorg.top", "vrabli.com",
        "vremonte24-store.com", "vrmtr.com", "vsimcard.com", "vssms.com",
        "vteachesb.com", "vualta.com", "vubby.com", "vwinfotography.com",
        "vxmail2.net", "vxmail3.net", "vxxx.com", "w3internet.co.uk",
        "w3mailbox.com", "w4i.org", "w9f.de", "w9y9640c.com",
        "wakingdaily.com", "walala.org", "walkmail.net", "walkmail.ru",
        "wallnsider.com", "wanko.be", "want2lov.us", "wantplay.site",
        "warau-kadode.com", "warmmail.com", "warpmail.net",
        "warriormail.com", "warunkpinter.com", "watch-harry-potter.com",
        "watchever.biz", "watchironman3onlinefreefullmovie.com",
        "wavepro.biz", "wazabi.club", "wbdev.tech", "wcpe.net",
        "webtrip.ch", "webuser.in", "wee.my", "weg-werfmail.de",
        "wegwerf-email.net", "wegwerf-email.de", "wegwerf-mail.com",
        "wegwerf-mail.net", "wegwerf.ad", "wegwerf.emil.com",
        "wegwerf.mx", "wegwerfaleb.com", "wegwerfmail.de",
        "wegwerfmail.info", "wegwerfmail.net", "wegwerfmail.org",
        "wegwerpmail.com", "wegwrfmail.de", "wegwrfmail.net",
        "welikecookies.com", "wellhungup.com", "wem.com", "wesdom.com",
        "westnet.com", "wetrainbayarea.com", "wetrainbayarea.org",
        "wfgdfhj.tk", "wg0.com", "wh4f.org", "whatiaas.com",
        "whatifanalytics.com", "whatpaas.com", "whatsaas.com",
        "whiffles.org", "whopy.com", "whtjddn.33mail.com",
        "whyspam.me", "wibblesmith.com", "wicked.cricket", "widaryanto.info",
        "widget.gg", "wierie.tk", "wikidocuslava.ru", "wilemail.com",
        "willhackforfood.biz", "willselfdestruct.com", "wimsg.com",
        "winemaven.info", "wins.com.br", "wlist.cf", "wlist.ga",
        "wlist.gq", "wlist.ml", "wlist.tk", "wmail.cf", "wmail.ga",
        "wmail.gq", "wmail.ml", "wmail.tk", "wokcy.com", "wolfmission.com",
        "wollan.info", "wondermail.com", "woooowoooo.com",
        "wootap.ws", "wopc.xyz", "worldbreak.com", "wosmail.com",
        "wowappsite.com", "wowmail.com", "wq.kr", "wralawfirm.com",
        "writeme.com", "writeme.us", "wronghead.com", "wudet.ml",
        "wuespdj.xyz", "wupics.com", "wuzup.net", "wwjmp.com",
        "wwwnew.eu", "wxnw.net", "wyvernweb.com", "x1000webs.com",
        "x24.com", "xagloo.com", "xasmail.com", "xazmail.com",
        "xcompress.com", "xcpy.com", "xemaps.com", "xent.com",
        "xents.com", "xeroma.com", "xf.sluteen.com", "xing886.uu.gl",
        "xjoi.com", "xl.cx", "xmail.com", "xmail.net", "xmaily.com",
        "xmastime.com", "xn--9kq967o.com", "xob.com", "xomra.ga",
        "xomra.ml", "xost.us", "xoxox.cc", "xperiae5.com", "xrho.com",
        "xsmail.com", "xtra.com", "xue.xyz", "xufr.xyz", "xupit.zzn.com",
        "xvx.us", "xwaretech.com", "xwaretech.info", "xwaretech.net",
        "xww.ro", "xxi2.com", "xxolocanto.xyz", "xxx.xxx.xxx.xxx.com",
        "xy9ce.tk", "xyzfree.net", "xzx.xyz", "yabai-oppai.com",
        "yahmail.top", "yahoo.com", "yahoodashtick.com", "yall.com",
        "yalmail.com", "yamail.com", "yandex.com", "yapped.net",
        "yaqp.com", "ycare.de", "ycn.ro", "ye.igg.biz", "yedi.org",
        "yep.it", "yepmail.net", "yeup.net", "yewmail.com",
        "ygroup-mail.com", "yhg.biz", "yifan.net", "ymail.com",
        "ymail.net", "ymail.org", "ynmrealty.com", "yodx.com",
        "yogamaven.com", "yomail.com", "yoo.ro", "yopmail.com",
        "yopmail.fr", "yopmail.gq", "yopmail.net", "yopmail.org",
        "yopmail.pp.ua", "yopmail.usa.cc", "yordanmail.cf",
        "you-spam.com", "yougotgoated.com", "youmail.com", "youmailr.com",
        "youpymail.com", "yourdomain.com", "yourinbox.com",
        "yourmail.com", "yournightmare.com", "yours.com", "yourssa.com",
        "yoursubdomain.com", "yousendmail.com", "yourspamgoeshere.com",
        "yourt.xyz", "yourtube.email", "ytrr.xyz", "yuurok.com",
        "yxzx.net", "z1p.biz", "z5cpf.ga", "z5cpf.ml", "z86.ru",
        "z8zcx.ga", "z8zcx.ml", "zahuy.site", "zaep.dk", "zaktouni.fr",
        "zanima.me", "zap.la", "zaproxy.org", "zaragozagm.com",
        "zavio.nl", "zcs.esmtp.biz", "zebins.com", "zebins.eu",
        "zehnminutenmail.de", "zehnminutenmail.net", "zepp.dk",
        "zetahost.org", "zetmail.com", "zhcn.ga", "zhe.96.lt",
        "zhouemail.510520.org", "zickdo.nl", "zik.dj", "zipcad.com",
        "zipido.com", "zippymail.info", "zipsendtest.com", "zmail.com",
        "zmail.info", "zmaill.com", "zmi.li", "znatok.com", "zoaxe.com",
        "zoemail.com", "zoemail.net", "zoemail.org", "zoetropes.org",
        "zombie-hive.com", "zomg.info", "zoutlook.com", "zp.ua",
        "zqjvx.cf", "zqjvx.ga", "zqjvx.gq", "zqjvx.ml", "zqjvx.tk",
        "zumpomail.com", "zv69.com", "zxcv.com", "zxcvbnm.com",
        "zz.mu", "zzz.com", "zzzmail.com"
    };

    public static bool IsDisposable(string email)
    {
        if (string.IsNullOrWhiteSpace(email)) return false;
        var atIndex = email.LastIndexOf('@');
        if (atIndex < 0) return false;
        var domain = email[(atIndex + 1)..].Trim().ToLowerInvariant();
        if (string.IsNullOrEmpty(domain)) return false;
        return Domains.Contains(domain);
    }
}
