const disposableDomains = new Set([
  "mailinator.com", "guerrillamail.com", "10minutemail.com", "tempmail.com",
  "throwaway.email", "yopmail.com", "sharklasers.com", "trashmail.com",
  "temp-mail.org", "tempail.com", "maildrop.cc", "getnada.com",
  "mailtemp.net", "discard.email", "spamgourmet.com", "mytemp.email",
  "fakeinbox.com", "mailmetrash.com", "mailexpire.com", "tempinbox.com",
  "temporary-mail.net", "mailcatch.com", "spam.la", "mintemail.com",
  "sofort-mail.de", "mailnator.com", "wegwerfmail.de", "burnermail.io",
  "throam.com", "throwaway.email", "trashymail.com", "tyldd.com",
  "yopmail.fr", "yopmail.net", "ypmail.webarnak.fr.eu.org",
  "temp-mail.com", "temp-mail.de", "tempemail.net",
  "0-00.usa.cc", "0-mail.com", "0815.ru", "1-8.biz",
  "2prong.com", "3-6-3.net", "4nextmail.com", "60minutemail.com",
  "anonymbox.com", "armyspy.com", "binkmail.com", "bio-muesli.net",
  "bobmail.info", "bouncr.com", "boximail.com", "briefkasten2.de",
  "bsnow.net", "buffmail.com", "bulsmail.com", "chacuo.net",
  "chammy.info", "ckptr.com", "cool.fr.nf", "courrieltemporaire.com",
  "crapmail.org", "cust.in", "dacoolest.com", "deadaddress.com",
  "deadspam.com", "despam.it", "devnullmail.com", "dinkmail.com",
  "dodgeit.com", "dodgemail.de", "donemail.ru", "dump-email.info",
  "dumpandjunk.com", "dumpmail.de", "dumpyemail.com", "e4ward.com",
  "email-fake.cf", "email-jetable.fr", "email.cbes.net",
  "email60.com", "emailage.cf", "emaildienst.de", "emaildrop.io",
  "emailfake.ml", "emailias.com", "emailinfive.com", "emailisvalid.com",
  "emaillime.com", "emailmiser.com", "emailna.co", "emailo.pro",
  "emailondeck.com", "emailresort.com", "emails.ga",
  "emailsecurer.com", "emailsensei.com", "emailspam.cf",
  "emailtemporarios.com", "emailthe.net", "emailtmp.com",
  "emailto.de", "emailwarden.com", "emailx.at", "emailx.net",
  "emailz.cf", "ephemail.net", "ethereal.email", "explodemail.com",
  "fakeinbox.com", "fakemail.fr", "fakemailgenerator.com",
  "fakemailz.com", "fammix.com", "fansworldwide.de", "fantasymail.de",
  "figshot.com", "filzmail.com", "fivemail.de", "fizmail.com",
  "forgetmail.com", "fr33mail.info", "frapmail.com",
  "free-email.cf", "freemail.cf", "freemail.ms", "friendlymail.co.uk",
  "frogmail.com", "fuckingcheapstuff.com", "funnymail.de",
  "gaggle.email", "garbagemail.org", "garbage.com",
  "garliclife.com", "gelitik.in", "get1mail.com", "get2mail.com",
  "getairmail.com", "getmails.eu", "getnada.com",
  "getonemail.com", "getonemail.net", "ghosttexter.de",
  "ginzi.be", "ginzi.net", "ginzy.co.uk", "ginzy.eu",
  "gishpuppy.com", "gmial.com", "goemail.com", "goodjab.club",
  "goplay.com", "gorillaswithdirtyarmpits.com", "gotmail.com",
  "gotmail.net", "gotmail.org", "grabmail.com", "grr.la",
  "gsrv.co.uk", "guerrillamail.biz", "guerrillamail.com",
  "guerrillamail.de", "guerrillamail.net", "guerrillamail.org",
  "guerrillamailblock.com", "gustr.com", "harakirimail.com",
  "hartbot.de", "headstrong.de", "hehs.gd", "hellodream.mobi",
  "herp.in", "hidemail.de", "hidemail.pro", "hidemail.us",
  "hmamail.com", "hochsitze.com", "hopto.org", "hostcalls.com",
  "hotpop.com", "hubii-network.com", "humaility.com",
  "hushmail.com", "i2pmail.org", "icx.in", "ieatspam.eu",
  "ieatspam.info", "ignoremail.com", "imails.info", "inbox.si",
  "inboxalias.com", "inboxbear.com", "inboxclean.com",
  "inboxclean.org", "inboxed.pw", "inboxproxy.com",
  "incognitomail.com", "incognitomail.net", "incognitomail.org",
  "ind.st", "indieclad.com", "ineec.net", "info-radio.ml",
  "inggo.org", "instant-mail.de", "instant.email",
  "instantmail.de", "internetoftags.com", "ipoo.org",
  "irish2me.com", "iwi.net", "jajxz.com", "jetable.com",
  "jetable.fr.nf", "jetable.net", "jetable.org", "jnxjn.com",
  "jourrapide.com", "junk.to", "junk1e.com", "junkmail.ga",
  "junkmail.gq", "kademen.com", "kappala.info", "kasmail.com",
  "kaspop.com", "killmail.com", "killmail.net", "kimsdisk.com",
  "klerk.xyz", "klipschx12.com", "kobrandify.com", "koszmail.pl",
  "kulturbetrieb.info", "kurzepost.de", "l33r.eu", "labetteraverouge.at",
  "lastmail.co", "lastmail.com", "lazyinbox.com", "lazyinbox.us",
  "letthemeatspam.com", "lillemap.net", "litedrop.com", "lol.ovpn.to",
  "lolfisher.com", "lom.kr", "lookformail.cf", "lookformail.ga",
  "lr7.us", "lroid.com", "lukecarriere.com", "m4ilweb.info",
  "maboard.com", "magamail.com", "maido.pw", "mail-2-you.com",
  "mail-awt.de", "mail-box.com", "mail-c.tk",
  "mail.bccto.com", "mail.bccto.me", "mail.gen.pw",
  "mail.ht", "mail.md", "mail.wtf",
  "mail0.ga", "mail1a.de", "mail1web.org", "mail2rss.org",
  "mail2space.com", "mail22.club", "mail22.space", "mail2tor.com",
  "mail333.com", "mail4trash.com", "mail707.com", "mail72.com",
  "mailback.com", "mailbidon.com", "mailblocks.com", "mailbox2go.com",
  "mailbucket.org", "mailcat.biz", "mailcatch.com", "mailchop.com",
  "mailcker.com", "mailde.de", "mailde.info", "maildrop.cc",
  "maileater.com", "mailexpire.com", "mailfa.tk", "mailfall.com",
  "mailforspam.com", "mailfree.ga", "mailfree.gq", "mailfree.ml",
  "mailfree.tk", "mailgutter.com", "mailhazard.com", "mailhazard.us",
  "mailhz.me", "mailimate.com", "mailin8r.com", "mailinatar.com",
  "mailinbox.cf", "mailinbox.co", "mailinbox.ga",
  "mailinbox.ml", "mailinbox.tk", "mailismagic.com",
  "mailita.tk", "mailjunk.org", "mailmate.com",
  "mailme.ga", "mailme.gq", "mailme.ml", "mailme.tk",
  "mailmetrash.com", "mailmoat.com", "mailmoth.com",
  "mailnator.com", "mailna.win", "mailnow2.com",
  "mailnuo.com", "mailonaut.com", "mailorator.com",
  "mailorg.org", "mailox.fun", "mailpick.biz",
  "mailpooch.com", "mailquack.com", "mailsac.com",
  "mailscrap.com", "mailseal.de", "mailsent.net",
  "mailservice.ms", "mailshiv.com", "mailshuttle.com",
  "mailsiphon.com", "mailslapping.com", "mailspam.xyz",
  "maistupid.com", "mailsuck.org", "mailt.net",
  "mailt.one", "mailtag.com", "mailtemp.info", "mailtemp.net",
  "mailtempmx.com", "mailtemporaire.com", "mailtemporaire.fr",
  "mailto.plus", "mailtothis.com", "mailtraps.com",
  "mailtrash.net", "mailtrix.net", "mailtv.net", "mailtv.tv",
  "mailuniverse.co.uk", "mailv3.com", "mailvc.com", "mailvn.net",
  "mailwizz.com", "mailz.info", "mailzer.net",
  "manybrain.com", "mb14.net", "meantinc.com", "meltmail.com",
  "messagebeagle.de", "meximex.com", "mhzayt.online",
  "migmail.net", "migmail.pl", "migumail.com", "mijnhqmail.nl",
  "mintemail.com", "misterpinball.com", "ml8.ca",
  "moakt.co", "moakt.com", "moakt.ws", "mobileninja.co.uk",
  "moburl.com", "mockmyid.com", "moeri.org", "mohmal.com",
  "mohmal.im", "mohmal.in", "mohmal.tech", "molms.com",
  "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf",
  "monumentmail.com", "moonwake.com", "moot.es",
  "moreorcs.com", "mountainregionallibrary.net",
  "msgden.com", "msgos.com", "my10minutemail.com",
  "mycleaninbox.net", "myemailboxy.com", "mymailcrush.cf",
  "mymailcrush.ga", "mymailcrush.gq", "mymailcrush.ml",
  "mymailcrush.tk", "mymailoasis.com", "mytemp.email",
  "mytempemail.com", "mytrashmail.com", "nada.email",
  "nada.ltd", "negated.com", "neomailbox.com", "nepwk.com",
  "nervmich.net", "nervtmich.net", "netmails.com",
  "netmails.net", "neverbox.com", "nevermail.de",
  "nextstopvalhalla.com", "nincsmail.com", "nnh.com",
  "no-more-mail.com", "nobulk.com", "noclickemail.com",
  "nogmailspam.info", "nomail.cf", "nomail.ga",
  "nomail.gq", "nomail.ml", "nomail.tk", "nomail2me.com",
  "nomorespamemails.com", "nonspam.eu", "nonspammer.de",
  "noref.in", "nospam.ze.tc", "nospam4.us",
  "nospamfor.us", "nospammail.net", "nospamthanks.info",
  "notmail.com", "notmail.net", "notmail.org",
  "notrnailinator.com", "notsharingmy.info",
  "nowmymail.com", "nur-fuer-spam.de",
  "nwldx.com", "nwytg.net", "o2t4g.org",
  "obfusko.com", "obobbo.com", "odaymail.com",
  "odnorazovoe.ru", "oepia.com", "oerpub.org",
  "ohi.tw", "oida.icu", "okclprojects.com",
  "olegalo.com", "olypmall.ru", "omnievents.org",
  "one-time.email", "oneoffmail.com", "onewaymail.com",
  "onlatedotcom.com", "onmail.win", "onmailzone.com",
  "opayq.com", "opentrash.com", "otherinbox.com",
  "outlook.com", "outlok.com", "ownyourmail.com",
  "p71ce1m.com", "pa9e.com", "pancakemail.com",
  "papierkorb.me", "pastebitch.com", "pecinan.com",
  "pencalc.com", "petrn.com", "pfui.ru",
  "pimpedupmyspace.com", "piratehaven.org", "pleasenospam.com",
  "pleasure-point.de", "podmail.org", "poofy.org",
  "pookmail.com", "postonline.me", "powered.name",
  "privacy.net", "privatdemail.net", "privy-mail.com",
  "privymail.de", "proxymail.eu", "prtnx.com",
  "punkass.com", "puppetmail.de", "purple.ftp.sh",
  "putthisinyourspamdatabase.com", "quick-mail.info",
  "quickinbox.com", "quickmail.in", "quickmail.nl",
  "r3t1.xyz", "raak.xyz", "rackabazar.com",
  "raketenmail.de", "rancidhome.net", "rcpt.at",
  "reallymymail.com", "receiveee.com", "recode.me",
  "recyclemail.dk", "redfeathercrow.com", "refreshingbox.com",
  "rejectmail.com", "reliable-mail.com", "remail.cf",
  "remail.ga", "rhyta.com", "riddermark.de",
  "rklips.com", "rmqkr.net", "rnailinator.com",
  "ro.lt", "robertspcrepair.com", "rollindo.agency",
  "rotaniliam.com", "row.kaybees.eu", "rppkn.com",
  "rtrtr.com", "s0ny.net", "sackmail.org",
  "safersignup.de", "safetymail.info", "safetypost.de",
  "sanstr.com", "sast.ro", "saynotospams.com",
  "scatmail.com", "schachcomplex.com", "schafmail.de",
  "schmeisswege.de", "schrott-email.de", "scrmnto.com",
  "secoint.info", "secure-box.info", "secure-mail.cc",
  "selfdestructingmail.com", "send22u.info", "sendfree.org",
  "sendspamhere.com", "sent.as", "sent.at",
  "sent.com", "seomastergroup.com",
  "sharklasers.com", "shieldedmail.com", "shmeriously.com",
  "shortmail.net", "shotmail.ru", "showslow.de",
  "sibmail.com", "sijuan123.xyz", "sinnlos-mail.de",
  "sitzong.com", "skymailapp.com", "slaskpost.se",
  "slopsmail.com", "slushmail.com", "sly.io",
  "smashmail.de", "smellfear.com", "smellrear.com",
  "smtp99.com", "snaknoc.com", "snkmail.com",
  "sofort-mail.de", "sofortmail.de", "softpls.asia",
  "sogetthis.com", "soio.de", "soldieroftheinternet.com",
  "soloveo.com", "solution4u.com", "soodmail.com",
  "soodonims.com", "spam-be-gone.com", "spam-cleaner.com",
  "spam-corner.com", "spam-delete.com",
  "spam-free.eu", "spam-free24.com", "spam-free24.eu",
  "spam-free24.net", "spam-free24.org",
  "spam-go.ru", "spam-hub.com", "spam-lists.com",
  "spam-shelter.com", "spam-snake.com",
  "spam-stop.com", "spam.as",
  "spam.biz", "spam.com", "spam.de",
  "spam.la", "spam.net", "spam.org",
  "spam.su", "spam4.me", "spamail.de",
  "spamarrest.com", "spamavert.com", "spambob.com",
  "spambob.net", "spambob.org", "spambog.com",
  "spambog.de", "spambog.net", "spambog.ru",
  "spambooger.com", "spambox.info", "spambox.me",
  "spambox.org", "spambox.us", "spambox.xyz",
  "spamcannon.com", "spamcannon.net", "spamcero.com",
  "spamcon.org", "spamcorptastic.com", "spamcowboy.com",
  "spamcowboy.net", "spamcowboy.org", "spamday.com",
  "spamdecoy.net", "spameater.com", "spameater.org",
  "spamex.com", "spamfighter.de", "spamfighter.cf",
  "spamfighter.ga", "spamfighter.gq", "spamfighter.ml",
  "spamfighter.tk", "spamfree.eu", "spamfree24.com",
  "spamfree24.de", "spamfree24.eu", "spamfree24.info",
  "spamfree24.net", "spamfree24.org", "spamgoes.in",
  "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
  "spamhereplease.com", "spamherelotso.com", "spamhole.com",
  "spamify.com", "spaminator.de", "spamkill.info",
  "spaml.com", "spamlot.net", "spammail.com",
  "spammail.me", "spammotel.com", "spamobox.com",
  "spamoff.ftpsite.info", "spamsalad.in",
  "spamserver.info", "spamserver.net", "spamserver.org",
  "spamslice.com", "spamsphere.com", "spamspot.com",
  "spamstack.net", "spamster.org", "spamthis.co.uk",
  "spamthisplease.com", "spamtrail.com", "spamtrap.net",
  "spamtroll.net", "spamwc.de", "spamwc.ga",
  "spamwc.gq", "spamwc.ml", "spamx.su",
  "spamzilla.net", "spartapost.com", "spazmail.com",
  "speed.1s.fr", "spikio.com", "spindl-e.com",
  "squizzy.info", "squizzy.net", "sry.li",
  "stanford-edu.tk", "starlight-breaker.net",
  "startfu.com", "startkeys.com", "statdvr.com",
  "stathost.net", "steambot.net", "stinkefinger.net",
  "stop-my-spam.com", "streetwisemail.com", "stromox.com",
  "stuckmail.com", "stuffmail.de", "suburbanthug.com",
  "suckmyd.com", "sudur.info", "suioe.com",
  "super-auswahl.de", "supergreatmail.com", "superplatyna.com",
  "superrito.com", "superstachel.de", "suremail.info",
  "svk.jp", "sweetnamex.com", "swift-mail.com",
  "tagyourself.com", "talkinator.com", "taphear.com",
  "tb-on-line.net", "techemail.com", "techgroup.me",
  "teeom.com", "teewars.org", "tehe.com",
  "teleosaur.us", "teleworm.com", "teleworm.us",
  "temp-emails.com", "temp-mail.com", "temp-mail.de",
  "temp-mail.org", "temp-mail.pp.ua", "temp-mail.ru",
  "temp-mails.com", "tempail.com", "tempalt.com",
  "tempdomain.net", "tempe-mail.com", "tempemail.biz",
  "tempemail.co.za", "tempemail.com", "tempemail.net",
  "tempemail.org", "tempemailaddress.com", "tempemails.net",
  "tempinbox.co.uk", "tempinbox.com", "tempmail.co",
  "tempmail.de", "tempmail.eu", "tempmail.it",
  "tempmail.net", "tempmail.us", "tempmail.win",
  "tempmail.ws", "tempmail2.com", "tempmaildemo.com",
  "tempmailer.com", "tempmails.org", "tempmailz.com",
  "tempomail.fr", "temporarily.com",
  "temporary-email.com", "temporary-email.net",
  "temporary-email.org", "temporaryforwarding.com",
  "temporarymail.org", "temporarymailaddress.com",
  "tempr.email", "tempsky.com", "tempthe.net",
  "tempymail.com", "testohata.xyz", "thanksnospam.info",
  "thankyou2010.com", "thecloudindex.com", "thembones.com.au",
  "themostemail.com", "thescrappermovie.com", "theskymail.com",
  "thespamfather.com", "thismail.net", "thisurl.com",
  "tittibit.net", "tkeiyo.com", "tmail.com", "tmail.run",
  "tmail.ws", "tmailinator.com", "tmails.net",
  "tmpeml.info", "tmpmail.net", "tmpmail.org", "toiea.com",
  "tokem.co", "tonne.to", "toomail.biz", "toss.pw",
  "totalvista.com", "tqoai.com", "tqosi.com",
  "trash-2009.com", "trash-2010.com", "trash-mail.com",
  "trash-mail.de", "trash-me.com", "trash2009.com",
  "trash2010.com", "trash2011.com", "trash247.com",
  "trashbox.eu", "trashcanmail.com", "trashdevil.com",
  "trashdevil.de", "trashemail.de", "trashemails.de",
  "trashimail.de", "trashmail.at", "trashmail.com",
  "trashmail.de", "trashmail.io", "trashmail.me",
  "trashmail.net", "trashmail.org", "trashmail.ws",
  "trashmailer.com", "trashmails.com", "trashspam.com",
  "trashymail.com", "trashymail.net", "trbvm.com",
  "trbvn.com", "trbvo.com", "trialmail.de",
  "trickmail.net", "trimsj.com", "trungtamtoeic.com",
  "turual.com", "twinmail.de", "twkly.ml",
  "tyldd.com", "uacro.com", "uggsrock.com",
  "uguuchantele.com", "ukexample.com", "unicorn.com",
  "uprinse.com", "uroid.com", "us.af", "us.to",
  "ushijima1129.cf", "ushijima1129.ga", "ushijima1129.gq",
  "ushijima1129.ml", "ushijima1129.tk", "valemail.net",
  "vankin.de", "vctel.com", "vedula.com",
  "venompen.com", "ver0.cf", "ver0.ga", "ver0.gq",
  "ver0.ml", "ver0.tk", "vfemail.net", "vickaentb.com",
  "vifiac.com", "vip-mail.tk", "vipmail.name",
  "vipmail.pw", "vnedu.me", "voidbay.com",
  "volaj.com", "vomito.email", "vorgsdemail.ml",
  "vorgsdemail.tk", "vps911.net", "walala.org",
  "walkmail.net", "walkmail.ru", "wanko.be",
  "warmmail.com", "warpmail.net", "watchever.biz",
  "webemail.me", "webuser.in", "wee.my",
  "weg-werfmail.de", "wegwerf-email.net", "wegwerf-email.de",
  "wegwerf-mail.com", "wegwerf-mail.net",
  "wegwerfmail.de", "wegwerfmail.info", "wegwerfmail.net",
  "wegwerfmail.org", "wegwrfmail.de", "wegwrfmail.net",
  "wellhungup.com", "whatifanalytics.com", "whispermail.de",
  "wh4f.org", "whyspam.me", "willselfdestruct.com",
  "winemaven.info", "wronghead.com", "wuzup.net",
  "xagloo.com", "xemaps.com", "xents.com",
  "xmail.com", "xmaily.com", "xoxy.net",
  "xww.ro", "xyzfree.net", "yapped.net",
  "yep.it", "yogamaven.com", "yopmail.com",
  "yopmail.fr", "yopmail.gq", "yopmail.net",
  "yopmail.org", "yopmail.pp.ua", "ypmail.webarnak.fr.eu.org",
  "yt-google.com", "yuurok.com", "z1p.biz",
  "zebins.com", "zebins.eu", "zehnminutenmail.de",
  "zehnminutenmail.net", "zeitmail.de", "zetmail.com",
  "zickdo.nl", "zipcad.com", "zippymail.info",
  "zoaxe.com", "zoemail.com", "zoemail.net",
  "zoemail.org", "zombie-hive.com", "zomg.info",
  "zxcv.com", "zzz.com", "zzzmail.com"
]);

export function isDisposableEmail(email: string): boolean {
  const atIndex = email.lastIndexOf('@');
  if (atIndex < 0) return false;
  const domain = email.slice(atIndex + 1).trim().toLowerCase();
  return disposableDomains.has(domain);
}
